export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const ORDER_BURGER = 'ORDER_BURGER';

export const REINITIALIZE_STATE = 'REINITIALIZE_STATE';
export const INIT_PURCHASE = 'INIT_PURCHASE';
export const INIT_LOADING = 'INIT_LOADING';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
