export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const ORDER_BURGER = 'ORDER_BURGER';

export const REINITIALIZE_BURGER_STATE = 'REINITIALIZE_BURGER_STATE';
export const REINITIALIZE_ORDER_STATE = 'REINITIALIZE_ORDER_STATE';
export const INIT_PURCHASE = 'INIT_PURCHASE';
export const INIT_LOADING = 'INIT_LOADING';
export const INIT_REDIRECTED = 'INIT_REDIRECTED';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH = 'AUTH';
export const AUTH_REDIRECT_DISABLE = 'AUTH_REDIRECT_DISABLE';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const LOAD_LOCAL_STORAGE = 'LOAD_LOCAL_STORAGE';

export const CLOSE_SLIDER = 'CLOSE_SLIDER';
export const OPEN_SLIDER = 'OPEN_SLIDER';
